//! The struct for viewing Baseball data streams
//!
//! This sport was generated semi-automatically and may contain errors.
super::sport_builder!(
    Baseball,
    "Baseball",
    true,
    (
        main_clock_time,
        &str,
        1,
        "Main Clock Time (hh:mm/mm:ss/ss.t)",
        1,
        5,
        L,
        ""
    ),
    (
        main_clock_time_2,
        &str,
        2,
        "Main Clock Time (hh:mm:ss/mm:ss.t)",
        6,
        8,
        L,
        ""
    ),
    (
        main_time_out_tod,
        &str,
        3,
        "Main/Time Out/TOD (hh:mm/mm:ss/ss.t)",
        14,
        5,
        L,
        ""
    ),
    (
        main_time_out_tod_2,
        &str,
        4,
        "Main/Time Out/TOD (hh:mm:ss/mm:ss.t)",
        19,
        8,
        L,
        ""
    ),
    (
        main_clock_is_zero,
        bool,
        5,
        "Main Clock =0 (' ' or 'z')",
        27,
        1,
        L,
        ""
    ),
    (
        main_clock_stopped,
        bool,
        6,
        "Main Clock Stopped (' ' or 's')",
        28,
        1,
        L,
        ""
    ),
    (
        main_clock_time_out_horn,
        bool,
        7,
        "Main Clock/Time Out Horn (' ' or 'h')",
        29,
        1,
        L,
        ""
    ),
    (
        main_clock_horn,
        bool,
        8,
        "Main Clock Horn (' ' or 'h')",
        30,
        1,
        L,
        ""
    ),
    (
        time_out_horn,
        bool,
        9,
        "Time Out Horn (' ' or 'h')",
        31,
        1,
        L,
        ""
    ),
    (
        time_out_time,
        &str,
        10,
        "Time Out Time (mm:ss)",
        32,
        8,
        L,
        ""
    ),
    (
        time_of_day,
        &str,
        11,
        "Time of Day (hh:mm:ss)",
        40,
        8,
        L,
        ""
    ),
    (home_team_name, &str, 12, "Home Team Name", 48, 20, L, ""),
    (guest_team_name, &str, 13, "Guest Team Name", 68, 20, L, ""),
    (
        home_team_abbreviation,
        &str,
        14,
        "Home Team Abbreviation",
        88,
        10,
        L,
        "Future",
        deprecate
    ),
    (
        guest_team_abbreviation,
        &str,
        15,
        "Guest Team Abbreviation",
        98,
        10,
        L,
        "Future",
        deprecate
    ),
    (home_team_score, &str, 16, "Home Team Score", 108, 4, R, ""),
    (
        guest_team_score,
        &str,
        17,
        "Guest Team Score",
        112,
        4,
        R,
        ""
    ),
    (
        home_time_outs_left_full,
        i32,
        18,
        "Home Time Outs Left - Full",
        116,
        2,
        R,
        ""
    ),
    (
        home_time_outs_left_partial,
        i32,
        19,
        "Home Time Outs Left - Partial",
        118,
        2,
        R,
        ""
    ),
    (
        home_time_outs_left_television,
        i32,
        20,
        "Home Time Outs Left - Television",
        120,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_time_outs_left_total,
        i32,
        21,
        "Home Time Outs Left - Total",
        122,
        2,
        R,
        ""
    ),
    (
        guest_time_outs_left_full,
        i32,
        22,
        "Guest Time Outs Left - Full",
        124,
        2,
        R,
        ""
    ),
    (
        guest_time_outs_left_partial,
        i32,
        23,
        "Guest Time Outs Left - Partial",
        126,
        2,
        R,
        ""
    ),
    (
        guest_time_outs_left_television,
        i32,
        24,
        "Guest Time Outs Left - Television",
        128,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_time_outs_left_total,
        i32,
        25,
        "Guest Time Outs Left - Total",
        130,
        2,
        R,
        ""
    ),
    (
        home_time_out_indicator,
        bool,
        26,
        "Home Time Out Indicator (' ' or '<')",
        132,
        1,
        L,
        ""
    ),
    (
        home_time_out_text,
        &str,
        27,
        "Home Time Out Text (' ' or 'TIME')",
        133,
        4,
        L,
        ""
    ),
    (
        guest_time_out_indicator,
        bool,
        28,
        "Guest Time Out Indicator (' ' or '>')",
        137,
        1,
        L,
        ""
    ),
    (
        guest_time_out_text,
        &str,
        29,
        "Guest Time Out Text (' ' or 'TIME')",
        138,
        4,
        L,
        ""
    ),
    (inning, i32, 30, "Inning", 142, 2, R, ""),
    (
        inning_text,
        &str,
        31,
        "Inning Text ('1st ', '2nd ', '3rd ')",
        144,
        4,
        L,
        "Future",
        deprecate
    ),
    (
        inning_description,
        &str,
        32,
        "Inning Description ('Top of 1st ')",
        148,
        12,
        L,
        "Future",
        deprecate
    ),
    (
        internal_relay,
        &str,
        33,
        "Internal Relay (' ' or 'z', 's', 'h')",
        160,
        1,
        L,
        ""
    ),
    (
        ad_panel_caption_power,
        bool,
        34,
        "Ad Panel / Caption Power ('c')",
        161,
        1,
        L,
        ""
    ),
    (
        ad_panel_caption_num1,
        bool,
        35,
        "Ad Panel / Caption #1 (' ' or 'c')",
        162,
        1,
        L,
        ""
    ),
    (
        ad_panel_caption_num2,
        bool,
        36,
        "Ad Panel / Caption #2 (' ' or 'c')",
        163,
        1,
        L,
        ""
    ),
    (
        ad_panel_caption_num3,
        bool,
        37,
        "Ad Panel / Caption #3 (' ' or 'c')",
        164,
        1,
        L,
        "Future",
        deprecate
    ),
    (
        ad_panel_caption_num4,
        bool,
        38,
        "Ad Panel / Caption #4 (' ' or 'c')",
        165,
        1,
        L,
        "Future",
        deprecate
    ),
    (
        home_at_bat_indicator,
        bool,
        40,
        "Home At Bat Indicator (' ' or '>')",
        201,
        1,
        L,
        ""
    ),
    (
        guest_at_bat_indicator,
        bool,
        41,
        "Guest At Bat Indicator (' ' or '>')",
        202,
        1,
        L,
        ""
    ),
    (home_hits, i32, 42, "Home Hits", 203, 2, R, ""),
    (home_errors, i32, 43, "Home Errors", 205, 2, R, ""),
    (
        home_left_on_base,
        i32,
        44,
        "Home Left on Base",
        207,
        2,
        R,
        ""
    ),
    (guest_hits, i32, 45, "Guest Hits", 209, 2, R, ""),
    (guest_errors, i32, 46, "Guest Errors", 211, 2, R, ""),
    (
        guest_left_on_base,
        i32,
        47,
        "Guest Left on Base",
        213,
        2,
        R,
        ""
    ),
    (batter_number, i32, 48, "Batter Number", 215, 2, R, ""),
    (
        batter_average,
        &str,
        49,
        "Batter Average (x.xxx)",
        217,
        5,
        R,
        ""
    ),
    (ball, i32, 50, "Ball", 222, 1, R, ""),
    (strike, i32, 51, "Strike", 223, 1, R, ""),
    (out, i32, 52, "Out", 224, 1, R, ""),
    (hit_indicator, i32, 53, "Hit Indicator", 225, 1, R, ""),
    (error_indicator, i32, 54, "Error Indicator", 226, 1, R, ""),
    (
        hit_error_text,
        &str,
        55,
        "Hit/Error Text (' ', 'HIT', 'ERROR')",
        227,
        5,
        L,
        ""
    ),
    (
        error_position,
        &str,
        56,
        "Error Position",
        232,
        2,
        L,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num1,
        &str,
        57,
        "Inning Label - #1",
        234,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num2,
        &str,
        58,
        "Inning Label - #2",
        236,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num3,
        &str,
        59,
        "Inning Label - #3",
        238,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num4,
        &str,
        60,
        "Inning Label - #4",
        240,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num5,
        &str,
        61,
        "Inning Label - #5",
        242,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num6,
        &str,
        62,
        "Inning Label - #6",
        244,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num7,
        &str,
        63,
        "Inning Label - #7",
        246,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num8,
        &str,
        64,
        "Inning Label - #8",
        248,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num9,
        &str,
        65,
        "Inning Label - #9",
        250,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num10,
        &str,
        66,
        "Inning Label - #10",
        252,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num11,
        &str,
        67,
        "Inning Label - #11",
        254,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        inning_label_num12,
        &str,
        68,
        "Inning Label - #12",
        256,
        2,
        R,
        "I can't tell what type this should be. If you can test, please submit a PR/issue. Thanks.",
        deprecate
    ),
    (
        home_inning_score_num1,
        i32,
        69,
        "Home Inning Score - #1",
        258,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num2,
        i32,
        70,
        "Home Inning Score - #2",
        260,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num3,
        i32,
        71,
        "Home Inning Score - #3",
        262,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num4,
        i32,
        72,
        "Home Inning Score - #4",
        264,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num5,
        i32,
        73,
        "Home Inning Score - #5",
        266,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num6,
        i32,
        74,
        "Home Inning Score - #6",
        268,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num7,
        i32,
        75,
        "Home Inning Score - #7",
        270,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num8,
        i32,
        76,
        "Home Inning Score - #8",
        272,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num9,
        i32,
        77,
        "Home Inning Score - #9",
        274,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num10,
        i32,
        78,
        "Home Inning Score - #10",
        276,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num11,
        i32,
        79,
        "Home Inning Score - #11",
        278,
        2,
        R,
        ""
    ),
    (
        home_inning_score_num12,
        i32,
        80,
        "Home Inning Score - #12",
        280,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num1,
        i32,
        81,
        "Guest Inning Score - #1",
        282,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num2,
        i32,
        82,
        "Guest Inning Score - #2",
        284,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num3,
        i32,
        83,
        "Guest Inning Score - #3",
        286,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num4,
        i32,
        84,
        "Guest Inning Score - #4",
        288,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num5,
        i32,
        85,
        "Guest Inning Score - #5",
        290,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num6,
        i32,
        86,
        "Guest Inning Score - #6",
        292,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num7,
        i32,
        87,
        "Guest Inning Score - #7",
        294,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num8,
        i32,
        88,
        "Guest Inning Score - #8",
        296,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num9,
        i32,
        89,
        "Guest Inning Score - #9",
        298,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num10,
        i32,
        90,
        "Guest Inning Score - #10",
        300,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num11,
        i32,
        91,
        "Guest Inning Score - #11",
        302,
        2,
        R,
        ""
    ),
    (
        guest_inning_score_num12,
        i32,
        92,
        "Guest Inning Score - #12",
        304,
        2,
        R,
        ""
    ),
    (
        home_pitcher_number,
        i32,
        93,
        "Home Pitcher Number",
        306,
        2,
        R,
        ""
    ),
    (
        home_pitches_thrown_balls,
        i32,
        94,
        "Home Pitches Thrown - Balls",
        308,
        3,
        R,
        ""
    ),
    (
        home_pitches_thrown_strikes,
        i32,
        95,
        "Home Pitches Thrown - Strikes",
        311,
        3,
        R,
        ""
    ),
    (
        home_pitches_thrown_foul_ball,
        i32,
        96,
        "Home Pitches Thrown - Foul Ball",
        314,
        3,
        R,
        ""
    ),
    (
        home_pitches_thrown_in_play,
        i32,
        97,
        "Home Pitches Thrown - In Play",
        317,
        3,
        R,
        ""
    ),
    (
        home_pitches_thrown_total,
        i32,
        98,
        "Home Pitches Thrown - Total",
        320,
        3,
        R,
        ""
    ),
    (
        guest_pitcher_number,
        i32,
        99,
        "Guest Pitcher Number",
        323,
        2,
        R,
        ""
    ),
    (
        guest_pitches_thrown_balls,
        i32,
        100,
        "Guest Pitches Thrown - Balls",
        325,
        3,
        R,
        ""
    ),
    (
        guest_pitches_thrown_strikes,
        i32,
        101,
        "Guest Pitches Thrown - Strikes",
        328,
        3,
        R,
        ""
    ),
    (
        guest_pitches_thrown_foul_ball,
        i32,
        102,
        "Guest Pitches Thrown - Foul Ball",
        331,
        3,
        R,
        ""
    ),
    (
        guest_pitches_thrown_in_play,
        i32,
        103,
        "Guest Pitches Thrown - In Play",
        334,
        3,
        R,
        ""
    ),
    (
        guest_pitches_thrown_total,
        i32,
        104,
        "Guest Pitches Thrown - Total",
        337,
        3,
        R,
        ""
    ),
    (
        main_clock_time_3,
        &str,
        105,
        "Main Clock Time (hh/mm/ss)",
        340,
        2,
        R,
        ""
    ),
    (
        at_bat_or_main_clock_time,
        &str,
        106,
        "At Bat or Main Clock Time (hh/mm/ss)",
        342,
        2,
        R,
        ""
    )
);
