//! This sport was generated semi-automatically and may contain errors.
super::sport_builder!(
    Cricket,
    "Cricket",
    false,
    (
        main_clock_time,
        &str,
        1,
        "Main Clock Time (hh:mm/mm:ss)",
        1,
        5,
        L,
        ""
    ),
    (
        main_clock_time_2,
        &str,
        2,
        "Main Clock Time (hh:mm:ss/mm:ss.th)",
        6,
        8,
        L,
        ""
    ),
    (
        main_time_out_tod,
        &str,
        3,
        "Main/Time Out/TOD (hh:mm/mm:ss)",
        14,
        5,
        L,
        ""
    ),
    (
        main_time_out_tod_2,
        &str,
        4,
        "Main/Time Out/TOD (hh:mm:ss/mm:ss.th)",
        19,
        8,
        L,
        ""
    ),
    (
        main_clock_is_zero,
        bool,
        5,
        "Main Clock =0 (' ' or 'z')",
        27,
        1,
        L,
        ""
    ),
    (
        main_clock_stopped,
        bool,
        6,
        "Main Clock Stopped (' ' or 's')",
        28,
        1,
        L,
        ""
    ),
    (
        main_clock_time_out_horn,
        bool,
        7,
        "Main Clock/Time Out Horn (' ' or 'h')",
        29,
        1,
        L,
        ""
    ),
    (
        main_clock_horn,
        bool,
        8,
        "Main Clock Horn (' ' or 'h')",
        30,
        1,
        L,
        ""
    ),
    (
        time_out_horn,
        bool,
        9,
        "Time Out Horn (' ' or 'h')",
        31,
        1,
        L,
        ""
    ),
    (
        time_out_time,
        &str,
        10,
        "Time Out Time (mm:ss)",
        32,
        8,
        L,
        ""
    ),
    (
        time_of_day,
        &str,
        11,
        "Time of Day (hh:mm:ss)",
        40,
        8,
        L,
        ""
    ),
    (home_team_name, &str, 12, "Home Team Name", 48, 20, L, ""),
    (guest_team_name, &str, 13, "Guest Team Name", 68, 20, L, ""),
    (
        home_team_abbreviation,
        &str,
        14,
        "Home Team Abbreviation",
        88,
        10,
        L,
        "Future",
        deprecate
    ),
    (
        guest_team_abbreviation,
        &str,
        15,
        "Guest Team Abbreviation",
        98,
        10,
        L,
        "Future",
        deprecate
    ),
    (home_team_score, &str, 16, "Home Team Score", 108, 4, R, ""),
    (
        guest_team_score,
        &str,
        17,
        "Guest Team Score",
        112,
        4,
        R,
        ""
    )
    // (home_time_outs_left_full, /* missing */, 18, "Home Time Outs Left - Full", 116, 2, R, ""),
    // (home_time_outs_left_partial, /* missing */, 19, "Home Time Outs Left - Partial", 118, 2, R, ""),
    // (home_time_outs_left_television, /* missing */, 20, "Home Time Outs Left - Television", 120, 2, R, "Future", deprecate),
    // (home_time_outs_left_total, /* missing */, 21, "Home Time Outs Left - Total", 122, 2, R, ""),
    // (guest_time_outs_left_full, /* missing */, 22, "Guest Time Outs Left - Full", 124, 2, R, ""),
    // (guest_time_outs_left_partial, /* missing */, 23, "Guest Time Outs Left - Partial", 126, 2, R, ""),
    // (guest_time_outs_left_television, /* missing */, 24, "Guest Time Outs Left - Television", 128, 2, R, "Future", deprecate),
    // (guest_time_outs_left_total, /* missing */, 25, "Guest Time Outs Left - Total", 130, 2, R, ""),
    // (home_time_out_indicator, /* missing */, 26, "Home Time Out Indicator (' ' or '<')", 132, 1, L, ""),
    // (home_time_out_text, /* missing */, 27, "Home Time Out Text (' ' or 'TIME')", 133, 4, L, ""),
    // (guest_time_out_indicator, /* missing */, 28, "Guest Time Out Indicator (' ' or '>')", 137, 1, L, ""),
    // (guest_time_out_text, /* missing */, 29, "Guest Time Out Text (' ' or 'TIME')", 138, 4, L, ""),
    // (period, /* missing */, 30, "Period", 142, 2, R, ""),
    // (period_text, /* missing */, 31, "Period Text ('1st ', 'OT', 'OT/2')", 144, 4, L, "Future", deprecate),
    // (period_description, /* missing */, 32, "Period Description ('End of 1st')", 148, 12, L, "Future", deprecate),
    // (internal_relay, /* missing */, 33, "Internal Relay (' ' or 'z', 's', 'h')", 160, 1, L, ""),
    // (ad_panel_caption_power, /* missing */, 34, "Ad Panel / Caption Power ('c')", 161, 1, L, ""),
    // (ad_panel_caption_num1, /* missing */, 35, "Ad Panel / Caption #1 (' ' or 'c')", 162, 1, L, ""),
    // (ad_panel_caption_num2, /* missing */, 36, "Ad Panel / Caption #2 (' ' or 'c')", 163, 1, L, ""),
    // (ad_panel_caption_num3, /* missing */, 37, "Ad Panel / Caption #3 (' ' or 'c')", 164, 1, L, "Future", deprecate),
    // (ad_panel_caption_num4, /* missing */, 38, "Ad Panel / Caption #4 (' ' or 'c')", 165, 1, L, "Future", deprecate),
    // (inning, /* missing */, 40, "Inning", 201, 2, R, ""),
    // (home_at_bat_indicator, /* missing */, 41, "Home At Bat Indicator (' ' or '>')", 203, 1, L, ""),
    // (guest_at_bat_indicator, /* missing */, 42, "Guest At Bat Indicator (' ' or '>')", 204, 1, L, ""),
    // (home_total_score, /* missing */, 43, "Home Total Score", 205, 4, R, ""),
    // (guest_total_score, /* missing */, 44, "Guest Total Score", 209, 4, R, ""),
    // (current_batter_1_score, /* missing */, 45, "Current - Batter 1 Score", 213, 3, R, ""),
    // (current_batter_2_score, /* missing */, 46, "Current - Batter 2 Score", 216, 3, R, ""),
    // (current_batter_3_score, /* missing */, 47, "Current - Batter 3 Score", 219, 3, R, ""),
    // (current_batter_4_score, /* missing */, 48, "Current - Batter 4 Score", 222, 3, R, ""),
    // (current_batter_5_score, /* missing */, 49, "Current - Batter 5 Score", 225, 3, R, ""),
    // (current_batter_6_score, /* missing */, 50, "Current - Batter 6 Score", 228, 3, R, ""),
    // (current_batter_7_score, /* missing */, 51, "Current - Batter 7 Score", 231, 3, R, ""),
    // (current_batter_8_score, /* missing */, 52, "Current - Batter 8 Score", 234, 3, R, ""),
    // (current_batter_9_score, /* missing */, 53, "Current - Batter 9 Score", 237, 3, R, ""),
    // (current_batter_10_score, /* missing */, 54, "Current - Batter 10 Score", 240, 3, R, ""),
    // (current_batter_11_score, /* missing */, 55, "Current - Batter 11 Score", 243, 3, R, ""),
    // (current_extras, /* missing */, 56, "Current Extras", 246, 2, R, ""),
    // (current_inning_score, /* missing */, 57, "Current Inning Score", 248, 4, R, ""),
    // (current_overs_remaining, /* missing */, 58, "Current Overs Remaining", 252, 2, R, ""),
    // (current_wickets, /* missing */, 59, "Current Wickets", 254, 2, R, ""),
    // (current_left_batsman_number, /* missing */, 60, "Current - Left Batsman Number", 256, 2, R, ""),
    // (current_left_batsman_score, /* missing */, 61, "Current - Left Batsman Score", 258, 3, R, ""),
    // (current_right_batsman_number, /* missing */, 62, "Current - Right Batsman Number", 261, 2, R, ""),
    // (current_right_batsman_score, /* missing */, 63, "Current - Right Batsman Score", 263, 3, R, ""),
    // (home_num1_batter_1_score, /* missing */, 64, "Home #1 - Batter 1 Score", 266, 3, R, ""),
    // (home_num1_batter_2_score, /* missing */, 65, "Home #1 - Batter 2 Score", 269, 3, R, ""),
    // (home_num1_batter_3_score, /* missing */, 66, "Home #1 - Batter 3 Score", 272, 3, R, ""),
    // (home_num1_batter_4_score, /* missing */, 67, "Home #1 - Batter 4 Score", 275, 3, R, ""),
    // (home_num1_batter_5_score, /* missing */, 68, "Home #1 - Batter 5 Score", 278, 3, R, ""),
    // (home_num1_batter_6_score, /* missing */, 69, "Home #1 - Batter 6 Score", 281, 3, R, ""),
    // (home_num1_batter_7_score, /* missing */, 70, "Home #1 - Batter 7 Score", 284, 3, R, ""),
    // (home_num1_batter_8_score, /* missing */, 71, "Home #1 - Batter 8 Score", 287, 3, R, ""),
    // (home_num1_batter_9_score, /* missing */, 72, "Home #1 - Batter 9 Score", 290, 3, R, ""),
    // (home_num1_batter_10_score, /* missing */, 73, "Home #1 - Batter 10 Score", 293, 3, R, ""),
    // (home_num1_batter_11_score, /* missing */, 74, "Home #1 - Batter 11 Score", 296, 3, R, ""),
    // (home_num1_extras, /* missing */, 75, "Home #1 - Extras", 299, 2, R, ""),
    // (home_num1_inning_score, /* missing */, 76, "Home #1 - Inning Score", 301, 4, R, ""),
    // (home_num1_overs_remaining, /* missing */, 77, "Home #1 - Overs Remaining", 305, 2, R, ""),
    // (home_num1_wickets, /* missing */, 78, "Home #1 - Wickets", 307, 2, R, ""),
    // (home_num1_left_batsman_number, /* missing */, 79, "Home #1 - Left Batsman Number", 309, 2, R, ""),
    // (home_num1_right_batsman_number, /* missing */, 80, "Home #1 - Right Batsman Number", 311, 2, R, ""),
    // (home_num2_batter_1_score, /* missing */, 81, "Home #2 - Batter 1 Score", 313, 3, R, ""),
    // (home_num2_batter_2_score, /* missing */, 82, "Home #2 - Batter 2 Score", 316, 3, R, ""),
    // (home_num2_batter_3_score, /* missing */, 83, "Home #2 - Batter 3 Score", 319, 3, R, ""),
    // (home_num2_batter_4_score, /* missing */, 84, "Home #2 - Batter 4 Score", 322, 3, R, ""),
    // (home_num2_batter_5_score, /* missing */, 85, "Home #2 - Batter 5 Score", 325, 3, R, ""),
    // (home_num2_batter_6_score, /* missing */, 86, "Home #2 - Batter 6 Score", 328, 3, R, ""),
    // (home_num2_batter_7_score, /* missing */, 87, "Home #2 - Batter 7 Score", 331, 3, R, ""),
    // (home_num2_batter_8_score, /* missing */, 88, "Home #2 - Batter 8 Score", 334, 3, R, ""),
    // (home_num2_batter_9_score, /* missing */, 89, "Home #2 - Batter 9 Score", 337, 3, R, ""),
    // (home_num2_batter_10_score, /* missing */, 90, "Home #2 - Batter 10 Score", 340, 3, R, ""),
    // (home_num2_batter_11_score, /* missing */, 91, "Home #2 - Batter 11 Score", 343, 3, R, ""),
    // (home_num2_extras, /* missing */, 92, "Home #2 - Extras", 346, 2, R, ""),
    // (home_num2_inning_score, /* missing */, 93, "Home #2 - Inning Score", 348, 4, R, ""),
    // (home_num2_overs_remaining, /* missing */, 94, "Home #2 - Overs Remaining", 352, 2, R, ""),
    // (home_num2_wickets, /* missing */, 95, "Home #2 - Wickets", 354, 2, R, ""),
    // (home_num2_left_batsman_number, /* missing */, 96, "Home #2 - Left Batsman Number", 356, 2, R, ""),
    // (home_num2_right_batsman_number, /* missing */, 97, "Home #2 - Right Batsman Number", 358, 2, R, ""),
    // (guest_num1_batter_1_score, /* missing */, 98, "Guest #1 - Batter 1 Score", 360, 3, R, ""),
    // (guest_num1_batter_2_score, /* missing */, 99, "Guest #1 - Batter 2 Score", 363, 3, R, ""),
    // (guest_num1_batter_3_score, /* missing */, 100, "Guest #1 - Batter 3 Score", 366, 3, R, ""),
    // (guest_num1_batter_4_score, /* missing */, 101, "Guest #1 - Batter 4 Score", 369, 3, R, ""),
    // (guest_num1_batter_5_score, /* missing */, 102, "Guest #1 - Batter 5 Score", 372, 3, R, ""),
    // (guest_num1_batter_6_score, /* missing */, 103, "Guest #1 - Batter 6 Score", 375, 3, R, ""),
    // (guest_num1_batter_7_score, /* missing */, 104, "Guest #1 - Batter 7 Score", 378, 3, R, ""),
    // (guest_num1_batter_8_score, /* missing */, 105, "Guest #1 - Batter 8 Score", 381, 3, R, ""),
    // (guest_num1_batter_9_score, /* missing */, 106, "Guest #1 - Batter 9 Score", 384, 3, R, ""),
    // (guest_num1_batter_10_score, /* missing */, 107, "Guest #1 - Batter 10 Score", 387, 3, R, ""),
    // (guest_num1_batter_11_score, /* missing */, 108, "Guest #1 - Batter 11 Score", 390, 3, R, ""),
    // (guest_num1_extras, /* missing */, 109, "Guest #1 - Extras", 393, 2, R, ""),
    // (guest_num1_inning_score, /* missing */, 110, "Guest #1 - Inning Score", 395, 4, R, ""),
    // (guest_num1_overs_remaining, /* missing */, 111, "Guest #1 - Overs Remaining", 399, 2, R, ""),
    // (guest_num1_wickets, /* missing */, 112, "Guest #1 - Wickets", 401, 2, R, ""),
    // (guest_num1_left_batsman_number, /* missing */, 113, "Guest #1 - Left Batsman Number", 403, 2, R, ""),
    // (guest_num1_right_batsman_number, /* missing */, 114, "Guest #1 - Right Batsman Number", 405, 2, R, ""),
    // (guest_num2_batter_1_score, /* missing */, 115, "Guest #2 - Batter 1 Score", 407, 3, R, ""),
    // (guest_num2_batter_2_score, /* missing */, 116, "Guest #2 - Batter 2 Score", 410, 3, R, ""),
    // (guest_num2_batter_3_score, /* missing */, 117, "Guest #2 - Batter 3 Score", 413, 3, R, ""),
    // (guest_num2_batter_4_score, /* missing */, 118, "Guest #2 - Batter 4 Score", 416, 3, R, ""),
    // (guest_num2_batter_5_score, /* missing */, 119, "Guest #2 - Batter 5 Score", 419, 3, R, ""),
    // (guest_num2_batter_6_score, /* missing */, 120, "Guest #2 - Batter 6 Score", 422, 3, R, ""),
    // (guest_num2_batter_7_score, /* missing */, 121, "Guest #2 - Batter 7 Score", 425, 3, R, ""),
    // (guest_num2_batter_8_score, /* missing */, 122, "Guest #2 - Batter 8 Score", 428, 3, R, ""),
    // (guest_num2_batter_9_score, /* missing */, 123, "Guest #2 - Batter 9 Score", 431, 3, R, ""),
    // (guest_num2_batter_10_score, /* missing */, 124, "Guest #2 - Batter 10 Score", 434, 3, R, ""),
    // (guest_num2_batter_11_score, /* missing */, 125, "Guest #2 - Batter 11 Score", 437, 3, R, ""),
    // (guest_num2_extras, /* missing */, 126, "Guest #2 - Extras", 440, 2, R, ""),
    // (guest_num2_inning_score, /* missing */, 127, "Guest #2 - Inning Score", 442, 4, R, ""),
    // (guest_num2_overs_remaining, /* missing */, 128, "Guest #2 - Overs Remaining", 446, 2, R, ""),
    // (guest_num2_wickets, /* missing */, 129, "Guest #2 - Wickets", 448, 2, R, ""),
    // (guest_num2_left_batsman_number, /* missing */, 130, "Guest #2 - Left Batsman Number", 450, 2, R, ""),
    // (guest_num2_right_batsman_number, /* missing */, 131, "Guest #2 - Right Batsman Number", 452, 2, R, "")
);
