//! The struct for viewing Judo data streams
//!
//! This sport was generated semi-automatically and may contain errors.
super::sport_builder!(
    Judo,
    "Judo",
    false,
    (
        main_clock_time,
        &str,
        1,
        "Main Clock Time (mm:ss/ss.t)",
        1,
        5,
        L,
        ""
    ),
    (
        main_clock_time_2,
        &str,
        2,
        "Main Clock Time (mm:ss.t)",
        6,
        8,
        L,
        ""
    ),
    (
        main_blood_injury_tod,
        &str,
        3,
        "Main/Blood/Injury/TOD (mm:ss/ss.t)",
        14,
        5,
        L,
        ""
    ),
    (
        main_time_out_tod_2,
        &str,
        4,
        "Main/Blood/Injury/TOD (mm:ss.t)",
        19,
        8,
        L,
        ""
    ),
    (
        main_clock_is_zero,
        bool,
        5,
        "Main Clock =0 (' ' or 'z')",
        27,
        1,
        L,
        ""
    ),
    (
        main_clock_stopped,
        bool,
        6,
        "Main Clock Stopped (' ' or 's')",
        28,
        1,
        L,
        ""
    ),
    (
        main_clock_time_out_horn,
        bool,
        7,
        "Main Clock/Time Out Horn (' ' or 'h')",
        29,
        1,
        L,
        ""
    ),
    (
        main_clock_horn,
        bool,
        8,
        "Main Clock Horn (' ' or 'h')",
        30,
        1,
        L,
        ""
    ),
    (
        time_out_horn,
        bool,
        9,
        "Time Out Horn (' ' or 'h')",
        31,
        1,
        L,
        ""
    ),
    (
        time_out_time,
        &str,
        10,
        "Time Out Time (mm:ss)",
        32,
        8,
        L,
        ""
    ),
    (
        time_of_day,
        &str,
        11,
        "Time of Day (hh:mm:ss)",
        40,
        8,
        L,
        ""
    ),
    (home_team_name, &str, 12, "Home Team Name", 48, 20, L, ""),
    (guest_team_name, &str, 13, "Guest Team Name", 68, 20, L, ""),
    (
        home_team_abbreviation,
        &str,
        14,
        "Home Team Abbreviation",
        88,
        10,
        L,
        "Future",
        deprecate
    ),
    (
        guest_team_abbreviation,
        &str,
        15,
        "Guest Team Abbreviation",
        98,
        10,
        L,
        "Future",
        deprecate
    ),
    (home_team_score, &str, 16, "Home Team Score", 108, 4, R, ""),
    (
        guest_team_score,
        &str,
        17,
        "Guest Team Score",
        112,
        4,
        R,
        ""
    )
    // (home_time_outs_left_full, /* missing */, 18, "Home Time Outs Left - Full", 116, 2, R, ""),
    // (home_time_outs_left_partial, /* missing */, 19, "Home Time Outs Left - Partial", 118, 2, R, ""),
    // (home_time_outs_left_television, /* missing */, 20, "Home Time Outs Left - Television", 120, 2, R, "Future", deprecate),
    // (home_time_outs_left_total, /* missing */, 21, "Home Time Outs Left - Total", 122, 2, R, ""),
    // (guest_time_outs_left_full, /* missing */, 22, "Guest Time Outs Left - Full", 124, 2, R, ""),
    // (guest_time_outs_left_partial, /* missing */, 23, "Guest Time Outs Left - Partial", 126, 2, R, ""),
    // (guest_time_outs_left_television, /* missing */, 24, "Guest Time Outs Left - Television", 128, 2, R, "Future", deprecate),
    // (guest_time_outs_left_total, /* missing */, 25, "Guest Time Outs Left - Total", 130, 2, R, ""),
    // (home_time_out_indicator, /* missing */, 26, "Home Time Out Indicator (' ' or '<')", 132, 1, L, ""),
    // (home_time_out_text, /* missing */, 27, "Home Time Out Text (‘ ‘ or ‘TIME’)", 133, 4, L, ""),
    // (guest_time_out_indicator, /* missing */, 28, "Guest Time Out Indicator (' ' or '>')", 137, 1, L, ""),
    // (guest_time_out_text, /* missing */, 29, "Guest Time Out Text (‘ ‘ or ‘TIME’)", 138, 4, L, ""),
    // (period, /* missing */, 30, "Period", 142, 2, R, ""),
    // (period_text, /* missing */, 31, "Period Text ('1st ', 'OT', 'OT/2')", 144, 4, L, "Future", deprecate),
    // (period_description, /* missing */, 32, "Period Description ('End of 1st ')", 148, 12, L, "Future", deprecate),
    // (internal_relay, /* missing */, 33, "Internal Relay (' ' or 'z', 's', 'h')", 160, 1, L, ""),
    // (ad_panel_caption_power, /* missing */, 34, "Ad Panel / Caption Power ('c')", 161, 1, L, ""),
    // (ad_panel_caption_num1, /* missing */, 35, "Ad Panel / Caption #1 (' ' or 'c')", 162, 1, L, ""),
    // (ad_panel_caption_num2, /* missing */, 36, "Ad Panel / Caption #2 (' ' or 'c')", 163, 1, L, ""),
    // (ad_panel_caption_num3, /* missing */, 37, "Ad Panel / Caption #3 (' ' or 'c')", 164, 1, L, "Future", deprecate),
    // (ad_panel_caption_num4, /* missing */, 38, "Ad Panel / Caption #4 (' ' or 'c')", 165, 1, L, "Future", deprecate),
    // (osaekomi_time, /* missing */, 40, "Osaekomi Time (mm:ss)", 201, 8, L, ""),
    // (blue_osaekomi_ti_me, /* missing */, 41, "Blue Osaekomi Ti me (mm:ss)", 209, 5, L, ""),
    // (white_osaekomi_time, /* missing */, 42, "White Osaekomi Time (mm:ss)", 214, 5, L, ""),
    // (blue_osaekomi_indicator, /* missing */, 43, "Blue Osaekomi Indicator (' ' or '>')", 219, 1, L, ""),
    // (white_osaekomi_indicator, /* missing */, 44, "White Osaekomi Indicator (' ' or '<')", 220, 1, L, ""),
    // (blue_waza_ari, /* missing */, 45, "Blue Waza Ari", 221, 1, R, ""),
    // (blue_yuko, /* missing */, 46, "Blue Yuko", 222, 1, R, ""),
    // (blue_koka, /* missing */, 47, "Blue Koka", 223, 1, R, ""),
    // (white_waza_ari, /* missing */, 48, "White Waza Ari", 224, 1, R, ""),
    // (white_yuko, /* missing */, 49, "White Yuko", 225, 1, R, ""),
    // (white_koka, /* missing */, 50, "White Koka", 226, 1, R, ""),
    // (blue_ippon_indicator, /* missing */, 51, "Blue Ippon Indicator (' ' or '>')", 227, 1, L, ""),
    // (blue_win_indicator, /* missing */, 52, "Blue Win Indicator (' ' or '>')", 228, 1, L, ""),
    // (blue_win_text, /* missing */, 53, "Blue Win Text (' ' or 'WIN')", 229, 3, L, ""),
    // (white_ippon_indicator, /* missing */, 54, "White Ippon Indicator (' ' or '<')", 232, 1, L, ""),
    // (white_win_indicator, /* missing */, 55, "White Win Indicator (' ' or '<')", 233, 1, L, ""),
    // (white_win_text, /* missing */, 56, "White Win Text (' ' or 'WIN')", 234, 3, L, ""),
    // (blue_medical_indicator_1, /* missing */, 57, "Blue Medical Indicator 1 (' ' or '+')", 237, 1, L, ""),
    // (blue_medical_indicator_2, /* missing */, 58, "Blue Medical Indicator 2 (' ' or '+')", 238, 1, L, ""),
    // (white_medical_indicator_1, /* missing */, 59, "White medical Indicator 1 (' ' or '+')", 239, 1, L, ""),
    // (white_medical_indicator_2, /* missing */, 60, "White Medical Indicator 2 (' ' or '+')", 240, 1, L, ""),
    // (blue_keikoku_indicator, /* missing */, 61, "Blue Keikoku Indicator (' ' or '>')", 241, 1, L, ""),
    // (blue_chui_indicator, /* missing */, 62, "Blue Chui Indicator (' ' or '>')", 242, 1, L, ""),
    // (blue_shido_indicator, /* missing */, 63, "Blue Shido Indicator (' ' or '>')", 243, 1, L, ""),
    // (blue_penalty_text, /* missing */, 64, "Blue Penalty Text (' ' or 'penalty')", 244, 7, L, ""),
    // (white_keikoku_indicator, /* missing */, 65, "White Keikoku Indicator (' ' or '<')", 251, 1, L, ""),
    // (white_chui_indicator, /* missing */, 66, "White Chui Indicator (' ' or '<')", 252, 1, L, ""),
    // (white_shido_indicator, /* missing */, 67, "White Shido Indicator (' ' or '<')", 253, 1, L, ""),
    // (white_penalty_text, /* missing */, 68, "White Penalty Text (' ' or 'penalty')", 254, 7, L, "")
);
