//! The struct for viewing Karate data streams
//!
//! This sport was generated semi-automatically and may contain errors.
super::sport_builder!(
    Karate,
    "Karate",
    false,
    (
        main_clock_time,
        &str,
        1,
        "Main Clock Time (mm:ss/ss.t)",
        1,
        5,
        L,
        ""
    ),
    (
        main_clock_time_2,
        &str,
        2,
        "Main Clock Time (mm:ss.t)",
        6,
        8,
        L,
        ""
    ),
    (
        main_clock_tod,
        &str,
        3,
        "Main Clock/TOD (mm:ss/ss.t)",
        14,
        5,
        L,
        ""
    ),
    (
        main_time_out_tod_2,
        &str,
        4,
        "Main Clock/TOD (mm:ss.t)",
        19,
        8,
        L,
        ""
    ),
    (
        main_clock_is_zero,
        bool,
        5,
        "Main Clock =0 (' ' or 'z')",
        27,
        1,
        L,
        ""
    ),
    (
        main_clock_stopped,
        bool,
        6,
        "Main Clock Stopped (' ' or 's')",
        28,
        1,
        L,
        ""
    ),
    (
        main_clock_time_out_horn,
        bool,
        7,
        "Main Clock/Time Out Horn (' ' or 'h')",
        29,
        1,
        L,
        ""
    ),
    (
        main_clock_horn,
        bool,
        8,
        "Main Clock Horn (' ' or 'h')",
        30,
        1,
        L,
        ""
    ),
    (
        time_out_horn,
        bool,
        9,
        "Time Out Horn (' ' or 'h')",
        31,
        1,
        L,
        ""
    ),
    (
        time_out_time,
        &str,
        10,
        "Time Out Time (mm:ss)",
        32,
        8,
        L,
        ""
    ),
    (
        time_of_day,
        &str,
        11,
        "Time of Day (hh:mm:ss)",
        40,
        8,
        L,
        ""
    ),
    (home_team_name, &str, 12, "Home Team Name", 48, 20, L, ""),
    (guest_team_name, &str, 13, "Guest Team Name", 68, 20, L, ""),
    (
        home_team_abbreviation,
        &str,
        14,
        "Home Team Abbreviation",
        88,
        10,
        L,
        "Future",
        deprecate
    ),
    (
        guest_team_abbreviation,
        &str,
        15,
        "Guest Team Abbreviation",
        98,
        10,
        L,
        "Future",
        deprecate
    ),
    (home_team_score, &str, 16, "Home Team Score", 108, 4, R, ""),
    (
        guest_team_score,
        &str,
        17,
        "Guest Team Score",
        112,
        4,
        R,
        ""
    )
    // (home_time_outs_left_full, /* missing */, 18, "Home Time Outs Left - Full", 116, 2, R, ""),
    // (home_time_outs_left_partial, /* missing */, 19, "Home Time Outs Left - Partial", 118, 2, R, ""),
    // (home_time_outs_left_television, /* missing */, 20, "Home Time Outs Left - Television", 120, 2, R, "Future", deprecate),
    // (home_time_outs_left_total, /* missing */, 21, "Home Time Outs Left - Total", 122, 2, R, ""),
    // (guest_time_outs_left_full, /* missing */, 22, "Guest Time Outs Left - Full", 124, 2, R, ""),
    // (guest_time_outs_left_partial, /* missing */, 23, "Guest Time Outs Left - Partial", 126, 2, R, ""),
    // (guest_time_outs_left_television, /* missing */, 24, "Guest Time Outs Left - Television", 128, 2, R, "Future", deprecate),
    // (guest_time_outs_left_total, /* missing */, 25, "Guest Time Outs Left - Total", 130, 2, R, ""),
    // (home_time_out_indicator, /* missing */, 26, "Home Time Out Indicator (' ' or '<')", 132, 1, L, ""),
    // (home_time_out_text, /* missing */, 27, "Home Time Out Text (‘ ‘ or ‘TIME’)", 133, 4, L, ""),
    // (guest_time_out_indicator, /* missing */, 28, "Guest Time Out Indicator (' ' or '>')", 137, 1, L, ""),
    // (guest_time_out_text, /* missing */, 29, "Guest Time Out Text (‘ ‘ or ‘TIME’)", 138, 4, L, ""),
    // (period, /* missing */, 30, "Period", 142, 2, R, ""),
    // (period_text, /* missing */, 31, "Period Text ('1st ', 'OT', 'OT/2')", 144, 4, L, "Future", deprecate),
    // (period_description, /* missing */, 32, "Period Description ('End of 1st')", 148, 12, L, "Future", deprecate),
    // (internal_relay, /* missing */, 33, "Internal Relay (' ' or 'z', 's', 'h’)", 160, 1, L, ""),
    // (ad_panel_caption_power, /* missing */, 34, "Ad Panel / Caption Power ('c')", 161, 1, L, ""),
    // (ad_panel_caption_num1, /* missing */, 35, "Ad Panel / Caption #1 (' ' or 'c')", 162, 1, L, ""),
    // (ad_panel_caption_num2, /* missing */, 36, "Ad Panel / Caption #2 (' ' or 'c')", 163, 1, L, ""),
    // (ad_panel_caption_num3, /* missing */, 37, "Ad Panel / Caption #3 (' ' or 'c')", 164, 1, L, "Future", deprecate),
    // (ad_panel_caption_num4, /* missing */, 38, "Ad Panel / Caption #4 (' ' or 'c')", 165, 1, L, "Future", deprecate),
    // (red_wazari, /* missing */, 40, "Red Wazari (' ' or 'W')", 201, 1, R, ""),
    // (red_hansoku, /* missing */, 41, "Red Hansoku (' ' or 'H')", 202, 1, R, ""),
    // (red_mubobi, /* missing */, 42, "Red Mubobi (' ' or 'M')", 203, 1, R, ""),
    // (red_jogai, /* missing */, 43, "Red Jogai (' ' or 'J')", 204, 1, R, ""),
    // (white_wazari, /* missing */, 44, "White Wazari (' ' or 'W')", 205, 1, R, ""),
    // (white_hansoku, /* missing */, 45, "White Hansoku (' ' or 'H')", 206, 1, R, ""),
    // (white_mubobi, /* missing */, 46, "White Mubobi (' ' or 'M')", 207, 1, R, ""),
    // (white_jogai, /* missing */, 47, "White Jogai (' ' or 'J')", 208, 1, R, ""),
    // (red_win_indicator, /* missing */, 48, "Red Win Indicator (' ' or '>')", 209, 1, L, ""),
    // (white_win_indicator, /* missing */, 49, "White Win Indicator (' ' or '<')", 210, 1, L, "")
);
