//! This sport was generated semi-automatically and may contain errors.
super::sport_builder!(
    LaneTimer,
    "Lane Timer",
    false,
    (
        main_clock_time,
        &str,
        1,
        "Main Clock Time (mm:ss/ss.t)",
        1,
        5,
        L,
        ""
    ),
    (
        main_clock_time_2,
        &str,
        2,
        "Main Clock Time (mm:ss.t)",
        6,
        8,
        L,
        ""
    ),
    (
        main_clock_time_out_tod,
        &str,
        3,
        "Main Clock/Time Out/TOD (mm:ss/ss.t)",
        14,
        5,
        L,
        ""
    ),
    (
        main_time_out_tod_2,
        &str,
        4,
        "Main Clock/Time Out/TOD 
(mm:ss.t)",
        19,
        8,
        L,
        ""
    ),
    (
        main_clock_is_zero,
        bool,
        5,
        "Main Clock =0 (' ' or 'z')",
        27,
        1,
        L,
        ""
    ),
    (
        main_clock_stopped,
        bool,
        6,
        "Main Clock Stopped (' ' or 's')",
        28,
        1,
        L,
        ""
    ),
    (
        main_clock_time_out_horn,
        bool,
        7,
        "Main Clock/Time Out Horn (' ' or 'h')",
        29,
        1,
        L,
        ""
    ),
    (
        main_clock_horn,
        bool,
        8,
        "Main Clock Horn (' ' or 'h')",
        30,
        1,
        L,
        ""
    ),
    (
        time_out_horn,
        bool,
        9,
        "Time Out Horn (' ' or 'h')",
        31,
        1,
        L,
        ""
    ),
    (
        time_out_time,
        &str,
        10,
        "Time Out Time (mm:ss)",
        32,
        8,
        L,
        ""
    ),
    (
        time_of_day,
        &str,
        11,
        "Time of Day (hh:mm:ss)",
        40,
        8,
        L,
        ""
    ),
    (home_team_name, &str, 12, "Home Team Name", 48, 20, L, ""),
    (guest_team_name, &str, 13, "Guest Team Name", 68, 20, L, ""),
    (
        home_team_abbreviation,
        &str,
        14,
        "Home Team Abbreviation",
        88,
        10,
        L,
        "Future",
        deprecate
    ),
    (
        guest_team_abbreviation,
        &str,
        15,
        "Guest Team Abbreviation",
        98,
        10,
        L,
        "Future",
        deprecate
    ),
    (home_team_score, &str, 16, "Home Team Score", 108, 4, R, ""),
    (
        guest_team_score,
        &str,
        17,
        "Guest Team Score",
        112,
        4,
        R,
        ""
    )
    // (home_time_outs_left_full, /* missing */, 18, "Home Time Outs Left - Full", 116, 2, R, ""),
    // (home_time_outs_left_partial, /* missing */, 19, "Home Time Outs Left - Partial", 118, 2, R, ""),
    // (home_time_outs_left_television, /* missing */, 20, "Home Time Outs Left - Television", 120, 2, R, "Future", deprecate),
    // (home_time_outs_left_total, /* missing */, 21, "Home Time Outs Left - Total", 122, 2, R, ""),
    // (guest_time_outs_left_full, /* missing */, 22, "Guest Time Outs Left - Full", 124, 2, R, ""),
    // (guest_time_outs_left_partial, /* missing */, 23, "Guest Time Outs Left - Partial", 126, 2, R, ""),
    // (guest_time_outs_left_television, /* missing */, 24, "Guest Time Outs Left - Television", 128, 2, R, "Future", deprecate),
    // (guest_time_outs_left_total, /* missing */, 25, "Guest Time Outs Left - Total", 130, 2, R, ""),
    // (home_time_out_indicator, /* missing */, 26, "Home Time Out Indicator (' ' or '<')", 132, 1, L, ""),
    // (home_time_out_text, /* missing */, 27, "Home Time Out Text (‘ ‘ or ‘TIME’)", 133, 4, L, ""),
    // (guest_time_out_indicator, /* missing */, 28, "Guest Time Out Indicator (' ' or '>')", 137, 1, L, ""),
    // (guest_time_out_text, /* missing */, 29, "Guest Time Out Text (‘ ‘ or ‘TIME’)", 138, 4, L, ""),
    // (period, /* missing */, 30, "Period", 142, 2, R, ""),
    // (period_text, /* missing */, 31, "Period Text ('1st ', 'OT ', 'OT/2')", 144, 4, L, "Future", deprecate),
    // (period_description, /* missing */, 32, "Period Description ('End of 1st')", 148, 12, L, "Future", deprecate),
    // (internal_relay, /* missing */, 33, "Internal Relay (' ' or 'z', 's', 'h')", 160, 1, L, ""),
    // (ad_panel_caption_power, /* missing */, 34, "Ad Panel / Caption Power ('c')", 161, 1, L, ""),
    // (ad_panel_caption_num1, /* missing */, 35, "Ad Panel / Caption #1 (' ' or 'c')", 162, 1, L, ""),
    // (ad_panel_caption_num2, /* missing */, 36, "Ad Panel / Caption #2 (' ' or 'c')", 163, 1, L, ""),
    // (ad_panel_caption_num3, /* missing */, 37, "Ad Panel / Caption #3 (' ' or 'c')", 164, 1, L, "Future", deprecate),
    // (ad_panel_caption_num4, /* missing */, 38, "Ad Panel / Caption #4 (' ' or 'c')", 165, 1, L, "Future", deprecate),
    // (best_time, /* missing */, 40, "Best Time (mm:ss.dcm)", 201, 9, R, "Photocell Mode Only"),
    // (lane_1_position_num, /* missing */, 41, "Lane 1 - Position #", 210, 3, R, ""),
    // (lane_2_position_num, /* missing */, 42, "Lane 2 - Position #", 213, 3, R, ""),
    // (lane_3_position_num, /* missing */, 43, "Lane 3 - Position #", 216, 3, R, ""),
    // (lane_4_position_num, /* missing */, 44, "Lane 4 - Position #", 219, 3, R, ""),
    // (position_1_car_num, /* missing */, 45, "Position 1 - Car #", 222, 3, R, ""),
    // (position_2_car_num, /* missing */, 46, "Position 2 - Car #", 225, 3, R, ""),
    // (position_3_car_num, /* missing */, 47, "Position 3 - Car #", 228, 3, R, ""),
    // (position_4_car_num, /* missing */, 48, "Position 4 - Car #", 231, 3, R, ""),
    // (lane_1_total_time, /* missing */, 49, "Lane 1 - Total Time (mm:ss.dcm)", 234, 9, R, ""),
    // (lane_1_elapsed_time, /* missing */, 50, "Lane 1 - Elapsed Time (mm:ss.dcm)", 243, 9, R, "Future", deprecate),
    // (lane_1_reaction_time, /* missing */, 51, "Lane 1 - Reaction Time (mm:ss.dcm)", 252, 9, R, "Future", deprecate),
    // (lane_2_total_time, /* missing */, 52, "Lane 2 - Total Time (mm:ss.dcm)", 261, 9, R, ""),
    // (lane_2_elapsed_time, /* missing */, 53, "Lane 2 - Elapsed Time (mm:ss.dcm)", 270, 9, R, "Future", deprecate),
    // (lane_2_reaction_time, /* missing */, 54, "Lane 2 - Reaction Time (mm:ss.dcm)", 279, 9, R, "Future", deprecate),
    // (lane_3_total_time, /* missing */, 55, "Lane 3 - Total Time (mm:ss.dcm)", 288, 9, R, ""),
    // (lane_3_elapsed_time, /* missing */, 56, "Lane 3 - Elapsed Time (mm:ss.dcm)", 297, 9, R, "Future", deprecate),
    // (lane_3_reaction_time, /* missing */, 57, "Lane 3 - Reaction Time (mm:ss.dcm)", 306, 9, R, "Future", deprecate),
    // (lane_4_total_time, /* missing */, 58, "Lane 4 - Total Time (mm:ss.dcm)", 315, 9, R, ""),
    // (lane_4_elapsed_time, /* missing */, 59, "Lane 4 - Elapsed Time (mm:ss.dcm)", 324, 9, R, "Future", deprecate),
    // (lane_4_reaction_time, /* missing */, 60, "Lane 4 - Reaction Time (mm:ss.dcm)", 333, 9, R, "Future", deprecate),
    // (position_1_total_time, /* missing */, 61, "Position 1 - Total Time (mm:ss.dcm)", 342, 9, R, ""),
    // (position_1_elapsed_time, /* missing */, 62, "Position 1 - Elapsed Time (mm:ss.dcm)", 351, 9, R, "Future", deprecate),
    // (position_1_reaction_time, /* missing */, 63, "Position 1 - Reaction Time (mm:ss.dcm)", 360, 9, R, "Future", deprecate),
    // (position_2_total_time, /* missing */, 64, "Position 2 - Total Time (mm:ss.dcm)", 369, 9, R, ""),
    // (position_2_elapsed_time, /* missing */, 65, "Position 2 - Elapsed Time (mm:ss.dcm)", 378, 9, R, "Future", deprecate),
    // (position_2_reaction_time, /* missing */, 66, "Position 2 - Reaction Time (mm:ss.dcm)", 387, 9, R, "Future", deprecate),
    // (position_3_total_time, /* missing */, 67, "Position 3 - Total Time (mm:ss.dcm)", 396, 9, R, ""),
    // (position_3_elapsed_time, /* missing */, 68, "Position 3 - Elapsed Time (mm:ss.dcm)", 405, 9, R, "Future", deprecate),
    // (position_3_reaction_time, /* missing */, 69, "Position 3 - Reaction Time (mm:ss.dcm)", 414, 9, R, "Future", deprecate),
    // (position_4_total_time, /* missing */, 70, "Position 4 - Total Time (mm:ss.dcm)", 423, 9, R, ""),
    // (position_4_elapsed_time, /* missing */, 71, "Position 4 - Elapsed Time (mm:ss.dcm)", 432, 9, R, "Future", deprecate),
    // (position_4_reaction_time, /* missing */, 72, "Position 4 - Reaction Time (mm:ss.dcm)", 441, 9, R, "Future", deprecate),
    // (lane_1_dq_status, /* missing */, 73, "Lane 1 - DQ Status (' ' or 'D')", 450, 1, R, ""),
    // (lane_2_dq_status, /* missing */, 74, "Lane 2 - DQ Status (' ' or 'D')", 451, 1, R, ""),
    // (lane_3_dq_status, /* missing */, 75, "Lane 3 - DQ Status (' ' or 'D')", 452, 1, R, ""),
    // (lane_4_dq_status, /* missing */, 76, "Lane 4 - DQ Status (' ' or 'D')", 453, 1, R, "")
);
