//! The struct for soccer's accessors (include a simple version)
//!
//! This sport was generated semi-automatically and may contain errors.
super::sport_builder!(
    Soccer,
    "Soccer",
    true,
    (
        main_clock_time,
        &str,
        1,
        "Main Clock Time (mm:ss/ss.t)",
        1,
        5,
        L,
        ""
    ),
    (
        main_clock_time_2,
        &str,
        2,
        "Main Clock Time (mm:ss.t)",
        6,
        8,
        L,
        ""
    ),
    (
        main_clock_time_out_tod,
        &str,
        3,
        "Main Clock/Time Out/TOD (mm:ss/ss.t)",
        14,
        5,
        L,
        ""
    ),
    (
        main_clock_time_out_tod_2,
        &str,
        4,
        "Main Clock/Time Out/TOD (mm:ss.t)",
        19,
        8,
        L,
        ""
    ),
    (
        main_clock_is_zero,
        bool,
        5,
        "Main Clock =0 (' ' or 'z')",
        27,
        1,
        L,
        ""
    ),
    (
        main_clock_stopped,
        bool,
        6,
        "Main Clock Stopped (' ' or 's')",
        28,
        1,
        L,
        ""
    ),
    (
        main_clock_time_out_horn,
        bool,
        7,
        "Main Clock/Time Out Horn (' ' or 'h')",
        29,
        1,
        L,
        ""
    ),
    (
        main_clock_horn,
        bool,
        8,
        "Main Clock Horn (' ' or 'h')",
        30,
        1,
        L,
        ""
    ),
    (
        time_out_horn,
        bool,
        9,
        "Time Out Horn (' ' or 'h')",
        31,
        1,
        L,
        ""
    ),
    (
        time_out_time,
        &str,
        10,
        "Time Out Time (mm:ss)",
        32,
        8,
        L,
        ""
    ),
    (
        time_of_day,
        &str,
        11,
        "Time of Day (hh:mm:ss)",
        40,
        8,
        L,
        ""
    ),
    (home_team_name, &str, 12, "Home Team Name", 48, 20, L, ""),
    (guest_team_name, &str, 13, "Guest Team Name", 68, 20, L, ""),
    (
        home_team_abbreviation,
        &str,
        14,
        "Home Team Abbreviation",
        88,
        10,
        L,
        "Future",
        deprecate
    ),
    (
        guest_team_abbreviation,
        &str,
        15,
        "Guest Team Abbreviation",
        98,
        10,
        L,
        "Future",
        deprecate
    ),
    (home_team_score, &str, 16, "Home Team Score", 108, 4, R, ""),
    (
        guest_team_score,
        &str,
        17,
        "Guest Team Score",
        112,
        4,
        R,
        ""
    ),
    (
        home_time_outs_left_full,
        i32,
        18,
        "Home Time Outs Left - Full",
        116,
        2,
        R,
        ""
    ),
    (
        home_time_outs_left_partial,
        i32,
        19,
        "Home Time Outs Left - Partial",
        118,
        2,
        R,
        ""
    ),
    (
        home_time_outs_left_television,
        i32,
        20,
        "Home Time Outs Left - Television",
        120,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_time_outs_left_total,
        i32,
        21,
        "Home Time Outs Left - Total",
        122,
        2,
        R,
        ""
    ),
    (
        guest_time_outs_left_full,
        i32,
        22,
        "Guest Time Outs Left - Full",
        124,
        2,
        R,
        ""
    ),
    (
        guest_time_outs_left_partial,
        i32,
        23,
        "Guest Time Outs Left - Partial",
        126,
        2,
        R,
        ""
    ),
    (
        guest_time_outs_left_television,
        i32,
        24,
        "Guest Time Outs Left - Television",
        128,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_time_outs_left_total,
        i32,
        25,
        "Guest Time Outs Left - Total",
        130,
        2,
        R,
        ""
    ),
    (
        home_time_out_indicator,
        bool,
        26,
        "Home Time Out Indicator (' ' or '<')",
        132,
        1,
        L,
        ""
    ),
    (
        home_time_out_text,
        &str,
        27,
        "Home Time Out Text (‘ ‘ or ‘TIME’)",
        133,
        4,
        L,
        ""
    ),
    (
        guest_time_out_indicator,
        bool,
        28,
        "Guest Time Out Indicator (' ' or '>')",
        137,
        1,
        L,
        ""
    ),
    (
        guest_time_out_text,
        &str,
        29,
        "Guest Time Out Text (‘ ‘ or ‘TIME’)",
        138,
        4,
        L,
        ""
    ),
    (half, i32, 30, "Half", 142, 2, R, ""),
    (
        half_text,
        &str,
        31,
        "Half Text ('1st ', 'OT', 'OT/2')",
        144,
        4,
        L,
        "Future",
        deprecate
    ),
    (
        half_description,
        &str,
        32,
        "Half Description ('End of 1st ')",
        148,
        12,
        L,
        "Future",
        deprecate
    ),
    (
        internal_relay,
        &str,
        33,
        "Internal Relay (' ' or 'z', 's', 'h')",
        160,
        1,
        L,
        ""
    ),
    (
        ad_panel_caption_power,
        bool,
        34,
        "Ad Panel / Caption Power ('c')",
        161,
        1,
        L,
        ""
    ),
    (
        ad_panel_caption_num1,
        bool,
        35,
        "Ad Panel / Caption #1 (' ' or 'c')",
        162,
        1,
        L,
        ""
    ),
    (
        ad_panel_caption_num2,
        bool,
        36,
        "Ad Panel / Caption #2 (' ' or 'c')",
        163,
        1,
        L,
        ""
    ),
    (
        ad_panel_caption_num3,
        bool,
        37,
        "Ad Panel / Caption #3 (' ' or 'c')",
        164,
        1,
        L,
        "Future",
        deprecate
    ),
    (
        ad_panel_caption_num4,
        bool,
        38,
        "Ad Panel / Caption #4 (' ' or 'c')",
        165,
        1,
        L,
        "Future",
        deprecate
    ),
    (
        home_possession_indicator,
        bool,
        40,
        "Home Possession Indicator (' ' or '<')",
        201,
        1,
        L,
        "Future",
        deprecate
    ),
    (
        home_possession_text,
        &str,
        41,
        "Home Possession Text (' ' or 'POSS')",
        202,
        4,
        L,
        "Future",
        deprecate
    ),
    (
        guest_possession_indicator,
        bool,
        42,
        "Guest Possession Indicator (' ' or '>')",
        206,
        1,
        L,
        "Future",
        deprecate
    ),
    (
        guest_possession_text,
        &str,
        43,
        "Guest Possession Text (' ' or 'POSS')",
        207,
        4,
        L,
        "Future",
        deprecate
    ),
    (
        home_score_period_1,
        i32,
        44,
        "Home Score - Period 1",
        211,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_score_period_2,
        i32,
        45,
        "Home Score - Period 2",
        213,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_score_period_3,
        i32,
        46,
        "Home Score - Period 3",
        215,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_score_period_4,
        i32,
        47,
        "Home Score - Period 4",
        217,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_score_period_5,
        i32,
        48,
        "Home Score - Period 5",
        219,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_score_period_6,
        i32,
        49,
        "Home Score - Period 6",
        221,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_score_period_7,
        i32,
        50,
        "Home Score - Period 7",
        223,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_score_period_8,
        i32,
        51,
        "Home Score - Period 8",
        225,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_score_period_9,
        i32,
        52,
        "Home Score - Period 9",
        227,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_score_current_period,
        i32,
        53,
        "Home Score - Current Period",
        229,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_period_1,
        i32,
        54,
        "Guest Score - Period 1",
        231,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_period_2,
        i32,
        55,
        "Guest Score - Period 2",
        233,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_period_3,
        i32,
        56,
        "Guest Score - Period 3",
        235,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_period_4,
        i32,
        57,
        "Guest Score - Period 4",
        237,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_period_5,
        i32,
        58,
        "Guest Score - Period 5",
        239,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_period_6,
        i32,
        59,
        "Guest Score - Period 6",
        241,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_period_7,
        i32,
        60,
        "Guest Score - Period 7",
        243,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_period_8,
        i32,
        61,
        "Guest Score - Period 8",
        245,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_period_9,
        i32,
        62,
        "Guest Score - Period 9",
        247,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_score_current_period,
        i32,
        63,
        "Guest Score - Current Period",
        249,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_shots_on_goal_1st_half,
        i32,
        64,
        "Home Shots On Goal - 1st Half",
        251,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_shots_on_goal_2nd_half,
        i32,
        65,
        "Home Shots On Goal - 2nd Half",
        253,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_shots_on_goal_overtime,
        i32,
        66,
        "Home Shots On Goal - Overtime",
        255,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_shots_on_goal_current,
        i32,
        67,
        "Home Shots On Goal - Current",
        257,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_shots_on_goal_total,
        i32,
        68,
        "Home Shots On Goal - Total",
        259,
        3,
        R,
        ""
    ),
    (
        home_saves_1st_half,
        i32,
        69,
        "Home Saves - 1st Half",
        262,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_saves_2nd_half,
        i32,
        70,
        "Home Saves - 2nd Half",
        264,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_saves_overtime,
        i32,
        71,
        "Home Saves - Overtime",
        266,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_saves_current,
        i32,
        72,
        "Home Saves - Current",
        268,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_saves_total,
        i32,
        73,
        "Home Saves - Total",
        270,
        3,
        R,
        ""
    ),
    (
        home_corner_kicks_1st_half,
        i32,
        74,
        "Home Corner Kicks - 1st Half",
        273,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_corner_kicks_2nd_half,
        i32,
        75,
        "Home Corner Kicks - 2nd Half",
        275,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_corner_kicks_overtime,
        i32,
        76,
        "Home Corner Kicks - Overtime",
        277,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_corner_kicks_current,
        i32,
        77,
        "Home Corner Kicks - Current",
        279,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_corner_kicks_total,
        i32,
        78,
        "Home Corner Kicks - Total",
        281,
        3,
        R,
        ""
    ),
    (
        home_penalty_1st_half,
        i32,
        79,
        "Home Penalty - 1st Half",
        284,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_penalty_2nd_half,
        i32,
        80,
        "Home Penalty - 2nd Half",
        286,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_penalty_overtime,
        i32,
        81,
        "Home Penalty - Overtime",
        288,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_penalty_current,
        i32,
        82,
        "Home Penalty - Current",
        290,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_penalty_total,
        i32,
        83,
        "Home Penalty - Total",
        292,
        3,
        R,
        ""
    ),
    (
        guest_shots_on_goal_1st_half,
        i32,
        84,
        "Guest Shots On Goal - 1st Half",
        295,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_shots_on_goal_2nd_half,
        i32,
        85,
        "Guest Shots On Goal - 2nd Half",
        297,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_shots_on_goal_overtime,
        i32,
        86,
        "Guest Shots On Goal - Overtime",
        299,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_shots_on_goal_current,
        i32,
        87,
        "Guest Shots On Goal - Current",
        301,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_shots_on_goal_total,
        i32,
        88,
        "Guest Shots On Goal - Total",
        303,
        3,
        R,
        ""
    ),
    (
        guest_saves_1st_half,
        i32,
        89,
        "Guest Saves - 1st Half",
        306,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_saves_2nd_half,
        i32,
        90,
        "Guest Saves - 2nd Half",
        308,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_saves_overtime,
        i32,
        91,
        "Guest Saves - Overtime",
        310,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_saves_current,
        i32,
        92,
        "Guest Saves - Current",
        312,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_saves_total,
        i32,
        93,
        "Guest Saves - Total",
        314,
        3,
        R,
        ""
    ),
    (
        guest_corner_kicks_1st_half,
        i32,
        94,
        "Guest Corner Kicks - 1st Half",
        317,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_corner_kicks_2nd_half,
        i32,
        95,
        "Guest Corner Kicks - 2nd Half",
        319,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_corner_kicks_overtime,
        i32,
        96,
        "Guest Corner Kicks - Overtime",
        321,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_corner_kicks_current,
        i32,
        97,
        "Guest Corner Kicks - Current",
        323,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_corner_kicks_total,
        i32,
        98,
        "Guest Corner Kicks - Total",
        325,
        3,
        R,
        ""
    ),
    (
        guest_penalty_1st_half,
        i32,
        99,
        "Guest Penalty - 1st Half",
        328,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_penalty_2nd_half,
        i32,
        100,
        "Guest Penalty - 2nd Half",
        330,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_penalty_overtime,
        i32,
        101,
        "Guest Penalty - Overtime",
        332,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_penalty_current,
        i32,
        102,
        "Guest Penalty - Current",
        334,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_penalty_total,
        i32,
        103,
        "Guest Penalty - Total",
        336,
        3,
        R,
        ""
    ),
    (
        home_corner_kicks_saves_1st_half,
        i32,
        104,
        "Home Corner Kicks/Saves - 1st Half",
        339,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_corner_kicks_saves_2nd_half,
        i32,
        105,
        "Home Corner Kicks/Saves - 2nd Half",
        341,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_corner_kicks_saves_overtime,
        i32,
        106,
        "Home Corner Kicks/Saves - Overtime",
        343,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_corner_kicks_saves_current,
        i32,
        107,
        "Home Corner Kicks/Saves - Current",
        345,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_corner_kicks_saves_total,
        i32,
        108,
        "Home Corner Kicks/Saves - Total",
        347,
        3,
        R,
        ""
    ),
    (
        guest_corner_kicks_saves_1st_half,
        i32,
        109,
        "Guest Corner Kicks/Saves - 1st Half",
        350,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_corner_kicks_saves_2nd_half,
        i32,
        110,
        "Guest Corner Kicks/Saves - 2nd Half",
        352,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_corner_kicks_saves_overtime,
        i32,
        111,
        "Guest Corner Kicks/Saves - Overtime",
        354,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_corner_kicks_saves_current,
        i32,
        112,
        "Guest Corner Kicks/Saves - Current",
        356,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_corner_kicks_saves_total,
        i32,
        113,
        "Guest Corner Kicks/Saves - Total",
        358,
        3,
        R,
        ""
    ),
    (
        home_fouls_1st_half,
        i32,
        114,
        "Home Fouls - 1st Half",
        361,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_fouls_2ndhalf,
        i32,
        115,
        "Home Fouls - 2ndHalf",
        363,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_fouls_overtime,
        i32,
        116,
        "Home Fouls - Overtime",
        365,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_fouls_current,
        i32,
        117,
        "Home Fouls - Current",
        367,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_fouls_total,
        i32,
        118,
        "Home Fouls - Total",
        369,
        3,
        R,
        ""
    ),
    (
        guest_fouls_1st_half,
        i32,
        119,
        "Guest Fouls - 1st Half",
        372,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_fouls_2nd_half,
        i32,
        120,
        "Guest Fouls - 2nd Half",
        374,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_fouls_overtime,
        i32,
        121,
        "Guest Fouls - Overtime",
        376,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_fouls_current,
        i32,
        122,
        "Guest Fouls - Current",
        378,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_fouls_total,
        i32,
        123,
        "Guest Fouls - Total",
        380,
        3,
        R,
        ""
    ),
    (
        home_penalty_tol_1st_half,
        i32,
        124,
        "Home Penalty/TOL - 1st Half",
        383,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_penalty_tol_2ndhalf,
        i32,
        125,
        "Home Penalty/TOL- 2ndHalf",
        385,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_penalty_tol_overtime,
        i32,
        126,
        "Home Penalty/TOL- Overtime",
        387,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_penalty_tol_current,
        i32,
        127,
        "Home Penalty/TOL- Current",
        389,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        home_penalty_tol_total,
        i32,
        128,
        "Home Penalty/TOL- Total",
        391,
        2,
        R,
        ""
    ),
    (
        guest_penalty_tol_1st_half,
        i32,
        129,
        "Guest Penalty/TOL- 1st Half",
        393,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_penalty_tol_2nd_half,
        i32,
        130,
        "Guest Penalty/TOL- 2nd Half",
        395,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_penalty_tol_overtime,
        i32,
        131,
        "Guest Penalty/TOL- Overtime",
        397,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_penalty_tol_current,
        i32,
        132,
        "Guest Penalty/TOL- Current",
        399,
        2,
        R,
        "Future",
        deprecate
    ),
    (
        guest_penalty_tol_total,
        i32,
        133,
        "Guest Penalty/TOL- Total",
        401,
        2,
        R,
        ""
    )
);

super::sport_builder!(
    SimpleSoccer,
    "Simple Soccer",
    true,
    (
        main_clock_time,
        &str,
        1,
        "Main Clock Time (mm:ss/ss.t)",
        1,
        5,
        L,
        ""
    ),
    (
        main_clock_time_2,
        &str,
        2,
        "Main Clock Time (mm:ss.t)",
        6,
        8,
        L,
        ""
    ),
    (
        main_clock_time_out_tod,
        &str,
        3,
        "Main Clock/Time Out/TOD (mm:ss/ss.t)",
        14,
        5,
        L,
        ""
    ),
    (
        main_clock_time_out_tod_2,
        &str,
        4,
        "Main Clock/Time Out/TOD (mm:ss.t)",
        19,
        8,
        L,
        ""
    ),
    (
        main_clock_is_zero,
        bool,
        5,
        "Main Clock =0 (' ' or 'z')",
        27,
        1,
        L,
        ""
    ),
    (
        main_clock_stopped,
        bool,
        6,
        "Main Clock Stopped (' ' or 's')",
        28,
        1,
        L,
        ""
    ),
    (
        main_clock_time_out_horn,
        bool,
        7,
        "Main Clock/Time Out Horn (' ' or 'h')",
        29,
        1,
        L,
        ""
    ),
    (
        main_clock_horn,
        bool,
        8,
        "Main Clock Horn (' ' or 'h')",
        30,
        1,
        L,
        ""
    ),
    (
        time_out_horn,
        bool,
        9,
        "Time Out Horn (' ' or 'h')",
        31,
        1,
        L,
        ""
    ),
    (
        time_out_time,
        &str,
        10,
        "Time Out Time (mm:ss)",
        32,
        8,
        L,
        ""
    ),
    (
        time_of_day,
        &str,
        11,
        "Time of Day (hh:mm:ss)",
        40,
        8,
        L,
        ""
    ),
    (home_team_name, &str, 12, "Home Team Name", 48, 20, L, ""),
    (guest_team_name, &str, 13, "Guest Team Name", 68, 20, L, ""),
    (home_team_score, &str, 16, "Home Team Score", 108, 4, R, ""),
    (
        guest_team_score,
        &str,
        17,
        "Guest Team Score",
        112,
        4,
        R,
        ""
    ),
    (
        home_time_outs_left_total,
        i32,
        21,
        "Home Time Outs Left - Total",
        122,
        2,
        R,
        ""
    ),
    (
        guest_time_outs_left_total,
        i32,
        25,
        "Guest Time Outs Left - Total",
        130,
        2,
        R,
        ""
    ),
    (
        home_time_out_indicator,
        bool,
        26,
        "Home Time Out Indicator (' ' or '<')",
        132,
        1,
        L,
        ""
    ),
    (
        guest_time_out_indicator,
        bool,
        28,
        "Guest Time Out Indicator (' ' or '>')",
        137,
        1,
        L,
        ""
    ),
    (half, i32, 30, "Half", 142, 2, R, ""),
    (
        half_text,
        &str,
        31,
        "Half Text ('1st ', 'OT', 'OT/2')",
        144,
        4,
        L,
        "Future",
        deprecate
    ),
    (
        half_description,
        &str,
        32,
        "Half Description ('End of 1st ')",
        148,
        12,
        L,
        "Future",
        deprecate
    )
);
